Update team and project pages for Fall 2020
uwblueprint/website pull request #345
Opened 2020-09-14 03:30 UTC by sherryhli

2020-09-14 12:33 UTC, meganniu requested changes

2020-09-14 12:33 UTC, meganniu commented on src/app/projects-page/projects-page.component.html
> +          For Blueprint, we’re focusing on streamlining the judging process of the competition by moving manual tasks
lol I don't know how much we're allowed to edit the project descriptions. Like are we allowed to edit for style as well as grammar?

if we can edit for style, I think we should replace this line with "Our team is focusing on streamlining..." because that's how the other projects start the description of their roles

2020-09-14 13:05 UTC, sherryhli commented on src/app/projects-page/projects-page.component.html
> +          For Blueprint, we’re focusing on streamlining the judging process of the competition by moving manual tasks
Sure will do, pretty minor change so I think it's ok. The "For Blueprint..." style was what we used for older projects and we're just reusing Dancefest's old description here.

2020-09-14 23:23 UTC, meganniu approved these changes
Ran this locally and everything seems good :)
Also checked all the name spellings

2020-09-15 00:15 UTC, sherryhli commented
Thanks for looking this over @meganniu!
Made some final edits (changed old project descriptions to be in past tense), if all looks good then I will merge

2020-09-15 00:37 UTC, meganniu approved these changes
Some small nits, but otherwise lgtm!

2020-09-15 00:37 UTC, meganniu commented on src/app/projects-page/projects-page.component.html
> +          adoption sites. Pet owners who upload mediocre photos of their pets significantly reduces the chance of
I think since the noun (Pet owners) is plural, 'reduces' should be 'reduce'

2020-09-15 00:37 UTC, meganniu commented on src/app/projects-page/projects-page.component.html
>            adoption. Tasked with alleviating this pain-point, our team at Blueprint built a mobile photo-taking app that
Should probably be "chance of adoption" instead of "adoption"

2020-09-15 00:37 UTC, meganniu commented on src/app/projects-page/projects-page.component.html
>            adoption. Tasked with alleviating this pain-point, our team at Blueprint built a mobile photo-taking app that
Idk if this is a stylistic thing, but I would suggest "pain point" instead of "pain-point"

2020-09-15 01:12 UTC, sherryhli commented on src/app/projects-page/projects-page.component.html
>            adoption. Tasked with alleviating this pain-point, our team at Blueprint built a mobile photo-taking app that
Wait I think we already have "chance of adoption"?

2020-09-15 01:21 UTC, sherryhli commented
Good catches! Fixed and merging now.

2020-09-15 01:21 UTC, merged

2020-09-15 01:52 UTC, meganniu commented on src/app/projects-page/projects-page.component.html
>            adoption. Tasked with alleviating this pain-point, our team at Blueprint built a mobile photo-taking app that
LOL i can't read